"""add chunks table

Revision ID: 57d6b7e44c2a
Revises: 8b0fe0a90e85
Create Date: 2026-06-21 22:16:44.620867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db_types import Vector


# revision identifiers, used by Alembic.
revision: str = '57d6b7e44c2a'
down_revision: Union[str, None] = '8b0fe0a90e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector's "vector" type only exists on Postgres; SQLite (tests/local
    # dev) gets a plain text column via app.db_types.Vector's fallback.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table('chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###
